### ISSUE TITLE
Windows packages are not available since 2024.02.26

### ISSUE THREAD

**Issue by jslee02** [conda-forge/folly-feedstock#176]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The Windows binaries are available up to version 2024.02.11, but there have been no updates since then. The [Windows builds](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=901088&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802) on Azure appear to be successful.

### Installed packages

```shell
N/A
```

### Environment info

```shell
win-64
```

**Comment by jjerphan** [comment]
FYI, Folly is not officially supporting Windows, and _untested_ on this platform. It also is admittedly [API and ABI unstable in between commits and not designed to be packaged as a shared library](https://github.com/facebook/folly?tab=readme-ov-file#build-notes) as it is the case on conda-forge.

**Comment by jslee02** [comment]
Thank you for the clarification and information. Building folly as a static library on Windows will work for my use cases. However, I am curious why the conda folly package is not being published after a specific version (2024.02.26).

Additionally, I am slightly confused by the statement that folly is not officially supporting Windows since the README states:

> folly supports gcc (5.1+), clang, or MSVC. It should run on Linux (x86-32, x86-64, and ARM), iOS, macOS, and Windows (x86-64). The CMake build is only tested on some of these platforms; at a minimum, we aim to support macOS and Linux (on the latest Ubuntu LTS release or newer.)

and it seems it's [being tested on Windows at the repo GitHub actions](https://github.com/facebook/folly/actions/workflows/getdeps_windows.yml).

I apologize if I am missing something here.

**Comment by jjerphan** [comment]
folly is mentioned to be unstable on Windows [in vcpkg](https://github.com/microsoft/vcpkg/blame/055721089e8037d4d617250814d11f881e557549/ports/folly/vcpkg.json#L5).

Also [some tests are disabled for Windows](https://github.com/facebook/folly/blob/f67559532c274fee8a84ab39d5711b422dc963a7/CMakeLists.txt#L889) ; those tests includes but not limited to the ones of:
- `F14Set`
- `ConcurrentHashMap`
- `ThreadPoolExecutors`
- `Future`
- `ThreadName`
- `FBString`
- `Hash`
- `ThreadCachedInt`
- `ThreadLocal`

**Comment by jslee02** [comment]
Ah, it's good to know. Supporting Windows can be a bit tricky at times :(

It would be great if the publishing for Windows could be fixed. Thank you for maintaining this folly-feedstock, btw!

**Comment by jjerphan** [comment]
I am not sure one of the maintainer of the feedstock ever use the Windows' builds, and unfortunately hardly have time to look into it. :confused:

To be honest, I am egoistically maintaining the feedstock to be able to adapt the build so that we can get ride of folly as a dependency for a project.

If you are interested, I would recommend co-maintaining the feedstock and sorting the problem. :slightly_smiling_face:

**Comment by jjerphan** [comment]
I think the concern is that there are releases whose Windows builds have not been published, even though their CI workflows were successful.

**Comment by xhochy** [comment]
…but they are published on anaconda.org. 😕

**Comment by jjerphan** [comment]
Oh, I missed that! They are indeed all visible on [anaconda's website](https://anaconda.org/conda-forge/folly/files) but some of them are missing on [prefix.dev's](https://prefix.dev/channels/conda-forge/packages/folly).

This is the case of [`folly-2024.05.02.00-h23e0033_0.conda`](https://anaconda.org/conda-forge/folly/2024.05.02.00/download/win-64/folly-2024.05.02.00-h23e0033_0.conda) for instance.

**Comment by xhochy** [comment]
These package show up if I run `micromamba search --platform win-64 folly` so it seems they are available.

**Comment by jjerphan** [comment]
Closing as completed.

@jslee02: feel free to reopen if this problems are still observed.
